'use client';

import { SEOHead } from "./SEOHead";

export function CookiePolicy() {
  return (
    <div className="w-full bg-slate-50 py-20 text-slate-800">
      <SEOHead
        title="Cookie Policy — Credit Consultant"
        description="Cookie Policy for Credit Consultant. Learn how we use cookies and similar technologies on our website."
        keywords="cookie policy, credit consultant cookies, tracking technologies"
      />

      <div className="mx-auto px-4 sm:px-6 lg:px-8">
        <div className="bg-white rounded-3xl shadow-sm border border-slate-200/80 p-8 md:p-12">
          <h1 className="text-3xl md:text-5xl font-extrabold text-slate-900 mb-4 tracking-tight">
            Cookie Policy
          </h1>
          <p className="text-sm text-slate-500 font-medium mb-12">
            Updated at 2026-08-13
          </p>

          <div className="space-y-8 text-base leading-relaxed text-slate-700">
            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4">Definitions and key terms</h2>
              <p className="mb-4">To help explain things as clearly as possible in this Cookie Policy, every time any of these terms are referenced, are strictly defined as:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
                <li><strong>Company:</strong> when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Credit Consultant, that is responsible for your information under this Cookie Policy.</li>
                <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Credit Consultant and use the services.</li>
                <li><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</li>
                <li><strong>Service:</strong> refers to the service provided by Credit Consultant as described in the relative terms (if available) and on this platform.</li>
                <li><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
                <li><strong>Website:</strong> Credit Consultant."’s" site, which can be accessed via this URL: creditconsultant.in</li>
                <li><strong>You:</strong> a person or entity that is registered with Credit Consultant to use the Services.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">Introduction</h2>
              <p>This Cookie Policy explains how Credit Consultant and its affiliates (collectively "Credit Consultant", "we", "us", and "ours"), use cookies and similar technologies to recognize you when you visit our website/app, including without limitation creditconsultant.in and any related URLs, mobile or localized versions and related domains / sub-domains ("Websites"). It explains what these technologies are and why we use them, as well as the choices for how to control them.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">What is a cookie?</h2>
              <p>A cookie is a small text file that is stored on your computer or other internet connected device in order to identify your browser, provide analytics, remember information about you such as your language preference or login information. They're completely safe and can't be used to run programs or deliver viruses to your device.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">Why do we use cookies?</h2>
              <p className="mb-4">We use first party and/or third party cookies on our website/app for various purposes such as:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>To facilitate the operation and functionality of our website/app;</li>
                <li>To improve your experience of our website/app and make navigating around them quicker and easier;</li>
                <li>To allow us to make a bespoke user experience for you and for us to understand what is useful or of interest to you;</li>
                <li>To analyze how our website/app is used and how best we can customize it;</li>
                <li>To identify future prospects and personalize marketing and sales interactions with it;</li>
                <li>To facilitate the tailoring of online advertising to your interests.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">What type of cookies does Credit Consultant use?</h2>
              <p className="mb-4">Cookies can either be session cookies or persistent cookies. A session cookie expires automatically when you close your browser. A persistent cookie will remain until it expires or you delete your cookies. Expiration dates are set in the cookies themselves; some may expire after a few minutes while others may expire after multiple years. Cookies placed by the website you’re visiting are called “first party cookies”.</p>
              <p className="mb-4">Strictly Necessary cookies are necessary for our website/app to function and cannot be switched off in our systems. They are essential in order to enable you to navigate around the website/app and use its features. If you remove or disable these cookies, we cannot guarantee that you will be able to use our website/app.</p>
              <p>We use the following types of cookies in our website/app:</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">Errors and Omissions Disclaimer</h2>
              <p className="mb-4">Credit Consultant is not responsible for any content, code or any other imprecision.</p>
              <p className="mb-4">Credit Consultant does not provide warranties or guarantees.</p>
              <p>In no event shall Credit Consultant be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. Credit Consultant reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">General Disclaimer</h2>
              <p>The Credit Consultant Service and its contents are provided "as is" and "as available" without any warranty or representations of any kind, whether express or implied. Credit Consultant is a distributor and not a publisher of the content supplied by third parties; as such, Credit Consultant exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible via the Credit Consultant Service. Without limiting the foregoing, Credit Consultant specifically disclaims all warranties and representations in any content transmitted on or in connection with the Credit Consultant Service or on sites that may appear as links on the Credit Consultant Service, or in the products provided as a part of, or otherwise in connection with, the Credit Consultant Service, including without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information given by Credit Consultant or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty. Price and availability information is subject to change without notice. Without limiting the foregoing, Credit Consultant does not warrant that the Credit Consultant Service will be uninterrupted, uncorrupted, timely, or error-free.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">Essential Cookies</h2>
              <p>We use essential cookies to make our website/app work. These cookies are strictly necessary to enable core functionality such as security, network management, your cookie preferences and accessibility. Without them you wouldn't be able to use basic services. You may disable these by changing your browser settings, but this may affect how the Websites function.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">Performance and Functionality Cookies</h2>
              <p>These cookies are used to enhance the performance and functionality of our website/app but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website/app as we would not be able to remember that you had logged in previously.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">Marketing Cookies</h2>
              <p>These account-based marketing cookies enable us to identify future prospects and personalize sales and marketing interactions with them.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">Analytics and Customization Cookies</h2>
              <p className="mb-4">These cookies collect information that is used to help us understand how our website/app is being used or how effective our marketing campaigns are, or to help us customize our website/app for you.</p>
              <p>We use cookies served by Google Analytics to collect limited data directly from end-user browsers to enable us to better understand your use of our website/app. Further information on how Google collects and uses this data can be found at: <a href="https://www.google.com/policies/privacy/partners/" className="text-blue-600 hover:underline">https://www.google.com/policies/privacy/partners/</a>. You can opt-out of all Google supported analytics on our Websites by visiting: <a href="https://tools.google.com/dlpage/gaoptout" className="text-blue-600 hover:underline">https://tools.google.com/dlpage/gaoptout</a>.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">Advertising Cookies</h2>
              <p>These cookies collect information over time about your online activity on the website/app and other online services to make online advertisements more relevant and effective to you. This is known as interest-based advertising. They also perform functions like preventing the same ad from continuously reappearing and ensuring that ads are properly displayed for advertisers. Without cookies, it’s really hard for an advertiser to reach its audience, or to know how many ads were shown and how many clicks they received.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">Social Media Cookies</h2>
              <p>These cookies are used when you share information using a social media sharing button or “like” button on our Site or you link your account or engage with our content on or through a social networking website such as Facebook, Twitter or Google+. The social network will record that you have done this. These cookies may also include certain code that has been placed on the platform to help track conversions from ads, optimize ads based on collected data, build targeted audiences for future ads, and remarket to qualified users who have already taken certain action on the platform.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">Third Party Cookies</h2>
              <p>Some cookies that have been set on our website/app are not set on a first party basis by Credit Consultant. The Websites can be embedded with content from third parties to serve advertising. These third party service providers may set their own cookies on your web browser. Third party service providers control many of the performance and functionality, advertising, marketing and analytics cookies described above. We do not control the use of these third party cookies as cookies can only be accessed by the third party that originally set them.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">How you can manage cookies?</h2>
              <p className="mb-4">Most browsers allow you to control cookies through their 'settings' preferences. However, if you limit the ability of websites to set cookies, you may worsen your overall user experience, since it will no longer be personalized to you. It may also stop you from saving customized settings like login information. Browser manufacturers provide help pages relating to cookie management in their products.</p>
              <p className="mb-4">Browser manufacturers provide help pages relating to cookie management in their products. Please see below for more information.</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Google Chrome</li>
                <li>Internet Explorer</li>
                <li>Mozilla Firefox</li>
                <li>Safari (Desktop)</li>
                <li>Safari (Mobile)</li>
                <li>Android Browser</li>
                <li>Opera</li>
                <li>Opera Mobile</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">Blocking and disabling cookies and similar technologies</h2>
              <p>Wherever you're located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser's help menu for more information.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">Changes To Our Cookie Policy</h2>
              <p>We may change our Service and policies, and we may need to make changes to this Cookie Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Cookie Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Cookie Policy. If you do not want to agree to this or any updated Cookie Policy, you can delete your account.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">Your Consent</h2>
              <p>By using our website/app, registering an account, or making a purchase, you hereby consent to our Cookie Policy and agree to its terms.</p>
            </div>

            <div className="bg-slate-100 p-6 rounded-2xl mt-12 border border-slate-200">
              <h2 className="text-2xl font-bold text-slate-900 mb-4">Contact Us</h2>
              <p className="mb-4">Don't hesitate to contact us if you have any questions regarding our Cookie Policy.</p>
              <ul className="space-y-2">
                <li><strong>Via Email:</strong> accounts@creditconsultant.in</li>
                <li><strong>Via Phone number:</strong> 9538049888</li>
                <li><strong>Via this Link:</strong> <a href="https://creditconsultant.in" className="text-blue-600 hover:underline">creditconsultant.in</a></li>
                <li><strong>Via this Address:</strong> 184, 15, 5th Main Rd, near police station, 4th Block, Jayanagar, Bengaluru, Karnataka 560011</li>
              </ul>
            </div>

          </div>
        </div>
      </div>
    </div>
  );
}