'use client';

import { SEOHead } from "./SEOHead";

export function Disclaimer() {
  return (
    <div className="w-full bg-slate-50 py-20 text-slate-800">
      <SEOHead
        title="Disclaimer — Credit Consultant"
        description="Disclaimer for Credit Consultant. Learn about our limited liability and general service disclaimers."
        keywords="disclaimer, credit consultant disclaimer, legal terms"
      />

      <div className="mx-auto px-4 sm:px-6 lg:px-8">
        <div className="bg-white rounded-3xl shadow-sm border border-slate-200/80 p-8 md:p-12">
          <h1 className="text-3xl md:text-5xl font-extrabold text-slate-900 mb-4 tracking-tight">
            Disclaimer
          </h1>
          <p className="text-sm text-slate-500 font-medium mb-12">
            Updated at 2026-08-14
          </p>

          <div className="space-y-8 text-base leading-relaxed text-slate-700">
            <p>
              Credit Consultant hereby grants you access to the website (https://www.creditconsultant.in/) and invites you to purchase the services offered here.
            </p>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">Definitions and key terms</h2>
              <p className="mb-4">To help explain things as clearly as possible in this Disclaimer, every time any of these terms are referenced, are strictly defined as:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
                <li><strong>Company:</strong> when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Credit Consultant, that is responsible for your information under this Disclaimer.</li>
                <li><strong>Service:</strong> refers to the service provided by Credit Consultant as described in the relative terms (if available) and on this platform.</li>
                <li><strong>Website:</strong> Credit Consultant's site, which can be accessed via this URL: https://www.creditconsultant.in/</li>
                <li><strong>You:</strong> a person or entity that is registered with Credit Consultant to use the Services.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">Limited liability</h2>
              <p className="mb-4">Credit Consultant endeavours to update and/or supplement the content of the website on a regular basis. Despite our care and attention, content may be incomplete and/or incorrect.</p>
              <p className="mb-4">The materials offered on the website are offered without any form of guarantee or claim to their correctness. These materials can be changed at any time without prior notice from Credit Consultant.</p>
              <p className="mb-4">Particularly, all prices on the website are stated subject to typing and programming errors. No liability is assumed for the implications of such errors. No agreement is concluded on the basis of such errors.</p>
              <p className="mb-4">Credit Consultant shall not bear any liability for hyperlinks to websites or services of third parties included on the website. From our website, you can visit other websites by following hyperlinks to such external sites. While we strive to provide only quality links to useful and ethical websites, we have no control over the content and nature of these sites. These links to other websites do not imply a recommendation for all the content found on these sites. Site owners and content may change without notice and may occur before we have the opportunity to remove a link which may have gone ‘bad’.</p>
              <p>Please be also aware that when you leave our website, other sites may have different privacy policies and terms which are beyond our control. Please be sure to check the Privacy Policies of these sites as well as their "Terms of Service" before engaging in any business or uploading any information.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">Errors and Omissions Disclaimer</h2>
              <p className="mb-4">Credit Consultant is not responsible for any content, code or any other imprecision.</p>
              <p className="mb-4">Credit Consultant does not provide warranties or guarantees.</p>
              <p>In no event shall Credit Consultant be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. Credit Consultant reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">General Disclaimer</h2>
              <p>The Credit Consultant Service and its contents are provided "as is" and "as available" without any warranty or representations of any kind, whether express or implied. Credit Consultant is a distributor and not a publisher of the content supplied by third parties; as such, Credit Consultant exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible via the Credit Consultant Service. Without limiting the foregoing, Credit Consultant specifically disclaims all warranties and representations in any content transmitted on or in connection with the Credit Consultant Service or on sites that may appear as links on the Credit Consultant Service, or in the products provided as a part of, or otherwise in connection with, the Credit Consultant Service, including without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information given by Credit Consultant or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty. Price and availability information is subject to change without notice. Without limiting the foregoing, Credit Consultant does not warrant that the Credit Consultant Service will be uninterrupted, uncorrupted, timely, or error-free.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">Your Consent</h2>
              <p>We've updated our Disclaimer to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website, registering an account, or making a purchase, you hereby consent to our Disclaimer and agree to its terms.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">Changes To Our Disclaimer</h2>
              <p>Should we update, amend or make any changes to this document so that they accurately reflect our Service and policies. Unless otherwise required by law, those changes will be prominently posted here. Then, if you continue to use the Service, you will be bound by the updated Disclaimer. If you do not want to agree to this or any updated Disclaimer, you can delete your account.</p>
            </div>

            <div className="bg-slate-100 p-6 rounded-2xl mt-12 border border-slate-200">
              <h2 className="text-2xl font-bold text-slate-900 mb-4">Contact Us</h2>
              <p className="mb-4">Don't hesitate to contact us if you have any questions regarding this Disclaimer.</p>
              <ul className="space-y-2">
                <li><strong>Via Email:</strong> accounts@creditconsultant.in</li>
                <li><strong>Via Phone number:</strong> 9538049888</li>
                <li><strong>Via this Link:</strong> <a href="https://creditconsultant.in" className="text-blue-600 hover:underline">https://creditconsultant.in</a></li>
                <li><strong>Via this Address:</strong> 184, 15, 5th Main Rd, near police station, 4th Block, Jayanagar, Bengaluru, Karnataka 560011</li>
              </ul>
            </div>

          </div>
        </div>
      </div>
    </div>
  );
}