'use client';

import { SEOHead } from "./SEOHead";

export function TermsOfService() {
  return (
    <div className="w-full bg-slate-50 py-20 text-slate-800">
      <SEOHead
        title="Terms of Service — Credit Consultant"
        description="Terms of Service for Credit Consultant. Learn how your personal information is collected, used, and disclosed."
        keywords="terms of service, credit consultant terms, data protection"
      />

      <div className="mx-auto px-4 sm:px-6 lg:px-8">
        <div className="bg-white rounded-3xl shadow-sm border border-slate-200/80 p-8 md:p-12">
          <h1 className="text-3xl md:text-5xl font-extrabold text-slate-900 mb-4 tracking-tight">
            Terms of Service
          </h1>
          <p className="text-sm text-slate-500 font-medium mb-12">
            Updated at 2026-08-13
          </p>

          <div className="space-y-8 text-base leading-relaxed text-slate-700">
            <p>
              Credit Consultant ("we," "our," or "us") is committed to protecting your privacy. This Terms of Service explains how your personal information is collected, used, and disclosed by Credit Consultant.
            </p>
            <p>
              This Terms of Service applies to our website, and its associated subdomains (collectively, our "Service") alongside our application, Credit Consultant. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Terms of Service and our Terms of Service.
            </p>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">Definitions and key terms</h2>
              <p className="mb-4">To help explain things as clearly as possible in this Terms of Service, every time any of these terms are referenced, are strictly defined as:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
                <li><strong>Company:</strong> when this policy mentions "Company," "we," "us," or "our," it refers to Credit Consultant, (184, 15, 5th Main Rd, near police station, 4th Block, Jayanagar, Bengaluru, Karnataka 560011) that is responsible for your information under this Terms of Service.</li>
                <li><strong>Country:</strong> where Credit Consultant or the owners/founders of Credit Consultant are based, in this case is India</li>
                <li><strong>Customer:</strong> refers to the company, organization or person that signs up to use the Credit Consultant Service to manage the relationships with your consumers or service users.</li>
                <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Credit Consultant and use the services.</li>
                <li><strong>IP address:</strong> Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</li>
                <li><strong>Personnel:</strong> refers to those individuals who are employed by Credit Consultant or are under contract to perform a service on behalf of one of the parties.</li>
                <li><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</li>
                <li><strong>Service:</strong> refers to the service provided by Credit Consultant as described in the relative terms (if available) and on this platform.</li>
                <li><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
                <li><strong>Website:</strong> Credit Consultant."'s" site, which can be accessed via this URL: www.creditconsultant.in</li>
                <li><strong>You:</strong> a person or entity that is registered with Credit Consultant to use the Services.</li>
              </ul>
              <p className="mt-4 text-sm text-slate-500">This Terms of Service was created with Termify.io</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">What Information Do We Collect?</h2>
              <p className="mb-4">We collect information from you when you visit our website/app, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.</p>
              <ul className="list-disc pl-6 space-y-1 mb-4">
                <li>Name / Username</li>
                <li>Phone Numbers</li>
                <li>Email Addresses</li>
                <li>Mailing Addresses</li>
                <li>Job Titles</li>
                <li>Billing Addresses</li>
                <li>Debit/credit card numbers</li>
                <li>Age</li>
                <li>Password</li>
              </ul>
              <p className="mb-4">We also collect information from mobile devices for a better user experience, although these features are completely optional:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li><strong>Photo Gallery (Pictures):</strong> Granting photo gallery access allows the user to upload any picture from their photo gallery, you can safely deny photo gallery access for this website/app.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">How Do We Use The Information We Collect?</h2>
              <p className="mb-4">Any of the information we collect from you may be used in one of the following ways:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>To personalize your experience (your information helps us to better respond to your individual needs)</li>
                <li>To improve our website/app (we continually strive to improve our website/app offerings based on the information and feedback we receive from you)</li>
                <li>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</li>
                <li>To process transactions</li>
                <li>To administer a contest, promotion, survey or other site feature</li>
                <li>To send periodic emails</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">When does Credit Consultant use end user information from third parties?</h2>
              <p className="mb-4">Credit Consultant will collect End User Data necessary to provide the Credit Consultant services to our customers.</p>
              <p>End users may voluntarily provide us with information they have made available on social media websites. If you provide us with any such information, we may collect publicly available information from the social media websites you have indicated. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">When does Credit Consultant use customer information from third parties?</h2>
              <p>We receive some information from the third parties when you contact us. For example, when you submit your email address to us to show interest in becoming a Credit Consultant customer, we receive information from a third party that provides automated fraud detection services to Credit Consultant. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">Do we share the information we collect with third parties?</h2>
              <p className="mb-4">We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest.</p>
              <p className="mb-4">We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and the website/app, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through the website/app. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.</p>
              <p className="mb-4">We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate general location and other technographics such as connection speed, whether you have visited the website/app in a shared location, and type of the device used to visit the website/app. They may aggregate information about our advertising and what you see on the website/app and then provide auditing, research and reporting for us and our advertisers. </p>
              <p>We may also disclose personal and non-personal information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal process (including subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and regulations. </p></div>
          </div>
        </div>
      </div>
    </div>
  );
}
